# Generated by Django 2.1 on 2018-08-25 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_client_prodarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.Client'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='prod_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.ProdArea'),
        ),
    ]
